{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "96171ba5-fcfe-458b-b57c-7834d627edcc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Brickfields Library System\n",
      "___________________________\n",
      "1. ADMINISTRATION LOGIN\n",
      "2. LIBRARIAN LOGIN\n",
      "3. LIBRARY MEMBER LOGIN\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "SELECT LOGIN OPTION NUMBER 1\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Brickfields Library System\n",
      "___________________________\n",
      "1. Super Administrator Login\n",
      "2. Administrator Login\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "SELECT ADMINISTRATOR LOGIN TYPE 1\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Brickfields Library System\n",
      "___________________________\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter Super Administrator Password sAd@kl2024\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Welcome Back!\n",
      "Brickfields Library System\n",
      "___________________________\n",
      "SUPER ADMINISTATOR HOME PAGE\n",
      "*****************************\n",
      "i. Administrator Information Management\n",
      "1. Member Information Management\n",
      "2. Librarian Information Management\n",
      "3. Exit\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Select an Option [i/1/2/3] i\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Brickfields Library System\n",
      "___________________________\n",
      "1. Add New Administrator Information\n",
      "2. View All Administrator Information\n",
      "3. Search Aministrator Information\n",
      "4. Edit Administrator Information\n",
      "5. Remove Administrator Information\n",
      "6. Log out\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Select an Option [1/2/3/4/5/6] 1\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Brickfields Library System\n",
      "___________________________\n",
      "Add New Administrator Information\n",
      "*********************************\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "ENTER ADMINISTRATOR NAME K\n",
      "ENTER ADMINISTRATOR ID L\n"
     ]
    }
   ],
   "source": [
    "# datetime was imported for current time and timedelta for time calculations in the laon book process\n",
    "from datetime import datetime, timedelta\n",
    "\n",
    "#function for the library title name\n",
    "def library_banner():\n",
    "    print('Brickfields Library System')\n",
    "    print('___________________________')\n",
    "    \n",
    "#function gives the administrator management options, 'while true' was used to loop the options after every input until logout where it breaks \n",
    "#as break function is used\n",
    "def admin_management():\n",
    "  while True :\n",
    "     library_banner()\n",
    "     print('1. Add New Administrator Information')\n",
    "     print('2. View All Administrator Information')\n",
    "     print('3. Search Aministrator Information')\n",
    "     print('4. Edit Administrator Information')\n",
    "     print('5. Remove Administrator Information')\n",
    "     print('6. Log out')\n",
    "     selection4 = input('Select an Option [1/2/3/4/5/6]')\n",
    "     if selection4 == '1':\n",
    "        new_admin()\n",
    "     elif selection4 == '2':\n",
    "        all_admin()\n",
    "     elif selection4 == '3':\n",
    "        search_admin()\n",
    "     elif selection4 == '4':\n",
    "        edit_admin()\n",
    "     elif selection4 == '5':\n",
    "        remove_admin()\n",
    "     elif selection4 == '6':\n",
    "        print('Logged Out')\n",
    "        break\n",
    "     else:\n",
    "        print('Invalid Option')\n",
    "#function to  add administrators by getting  input from the super administrator \n",
    "#and creates the file 'admin.txt' if not created or adds to it the inputs if it already exists\n",
    "#the current time is also recorded and added to the file\n",
    "def new_admin():\n",
    "    library_banner()\n",
    "    print('Add New Administrator Information')\n",
    "    print('*********************************')\n",
    "    adname = input('ENTER ADMINISTRATOR NAME')\n",
    "    adID = input('ENTER ADMINISTRATOR ID')\n",
    "    ademail = input('ENTER ADMINISTRATOR EMAIL')\n",
    "    timenow = datetime.now().strftime('%c')\n",
    "    with open('admin.txt', 'a+') as file:\n",
    "        file.write(f'{adname};{adID};{ademail};{timenow};\\n')\n",
    "        \n",
    "#function to open  an empty list and read the 'admin.txt' as it separates each single word data with ';'\n",
    "#the list is changed to a dictionary 'admindict' then converted bact to list 'adminlist'\n",
    "def admin(): \n",
    "    adminlist = []\n",
    "    with open('admin.txt','r') as file:\n",
    "      for line in file:\n",
    "        info1 = line.strip().split(';')\n",
    "        admindict = {'Name':info1[0], 'ID':info1[1],'Email':info1[2], 'Joined':info1[3]} \n",
    "        adminlist.append(admindict)\n",
    "    return adminlist\n",
    "#admin() function returns the list of administrator information, if the super administrator input matches the name of the administrator on the adminlist\n",
    "#the administrator information for the specific name is printed on the output\n",
    "def search_admin():\n",
    "    library_banner()\n",
    "    print('Search Administrator Information')\n",
    "    print('*********************************')\n",
    "    adminlist = admin()\n",
    "    ad_search = input('Enter Administrator name to search')\n",
    "    for i in adminlist:\n",
    "        if i['Name'] == ad_search:\n",
    "            print(f\"{i['Name']}, {i['ID']},{i['Email']},{i['Joined']}\")\n",
    "            \n",
    "#the administrator list is printed line by line for the user to refer to when editing\n",
    "#if the old name, ID, Email matches whats in the corresponding list ;the new name or ID or Email replaces it in the list\n",
    "#the new changes are then written in the file\n",
    "def edit_admin():\n",
    "    library_banner()\n",
    "    print('Edit Administrator Information')\n",
    "    print('*******************************')\n",
    "    adminlist = admin()\n",
    "    no = 1\n",
    "    for i in adminlist:\n",
    "      print(f\"{no}){i['Name']}, {i['ID']},{i['Email']},{i['Joined']}\")    \n",
    "      no += 1\n",
    "    oldname = input('Enter the Current Administrator Name')\n",
    "    newname = input('Enter New Administrator Name')\n",
    "    oldID = input('Enter the Current Administrator ID')\n",
    "    newID = input('Enter the New Administrator ID')\n",
    "    oldemail = input('Enter the Current Administrator Email')\n",
    "    newemail = input('Enter the New Administrator Email')\n",
    "    for line in adminlist:\n",
    "        if line['Name'] == oldname:\n",
    "            line['Name'] = newname\n",
    "        elif line['ID'] == oldID:\n",
    "            line['ID'] = newID\n",
    "        elif line['Email'] == oldemail:\n",
    "            line['Email'] = newemail \n",
    "            break\n",
    "    with open('admin.txt','w') as file:\n",
    "            for a in adminlist:\n",
    "                file.write(f\"{a['Name']};{a['ID']};{a['Email']};{a['Joined']};\\n\")\n",
    "                \n",
    "#the administrator list is printed line by line for the user to refer to when editing\n",
    "#if the input name corresponds with the name in the administrator list the other names apart from that one are shown in the output\n",
    "def remove_admin():\n",
    "    library_banner()\n",
    "    print('Delete Administrator Information')\n",
    "    print('*********************************')\n",
    "    adminlist = admin()\n",
    "    no = 1\n",
    "    for i in adminlist:\n",
    "      print(f\"{no}){i['Name']}, {i['ID']},{i['Email']},{i['Joined']}\")    \n",
    "      no += 1\n",
    "    deleteadmin = input('Enter Administrator Name to delete')\n",
    "    adminlist = [line for line in adminlist if line['Name'] != deleteadmin]\n",
    "    with open('admin.txt', 'w') as file:\n",
    "         for a in adminlist:\n",
    "             file.write(f\"{a['Name']};{a['ID']};{a['Email']};{a['Joined']};\\n\")\n",
    "             \n",
    "#all administrator list from admin.txt are iterated using the loop 'for i in adminlist'\n",
    "def all_admin():\n",
    "    print('View All Administrator Information')\n",
    "    print('***********************************')\n",
    "    adminlist = admin()\n",
    "    no = 1\n",
    "    for i in adminlist:\n",
    "        print(f\"{no}){i['Name']}, {i['ID']}, {i['Email']}, {i['Joined']}\")\n",
    "        no += 1 \n",
    "        \n",
    "#function gives the administrator management options, 'while true' was used to loop the options after every input until logout where it breaks \n",
    "#as break function is used\n",
    "def member_management():\n",
    "   while True:\n",
    "    library_banner()\n",
    "    print('1. Add New Member Information')\n",
    "    print('2. View All Member Information')\n",
    "    print('3. Search Member Information')\n",
    "    print('4. Edit Member Information')\n",
    "    print('5. Remove Member Information')\n",
    "    print('6. Log Out')\n",
    "    selection5 = input('Select an Option [1/2/3/4/5/6]')\n",
    "    if selection5 == '1':\n",
    "        new_member()\n",
    "    elif selection5 == '2':\n",
    "        all_member()\n",
    "    elif selection5 == '3':\n",
    "        search_member()\n",
    "    elif selection5 == '4':\n",
    "        edit_member()\n",
    "    elif selection5 == '5':\n",
    "        remove_member()\n",
    "    elif selection5 == '6':\n",
    "        print('Logged Out')\n",
    "        break\n",
    "    else:\n",
    "        print('Invalid Option')\n",
    "        \n",
    "#function to  add members by getting  input from the super administrator or administrator\n",
    "#and creates the file 'member.txt' if not created or adds to it the inputs if it already exists\n",
    "#the current time is also recorded and added to the file        \n",
    "def new_member():\n",
    "    library_banner()\n",
    "    print('Add New Member Information')\n",
    "    print('***********************')\n",
    "    memname = input('ENTER MEMBER NAME')\n",
    "    memID = input('ENTER MEMBER ID')\n",
    "    mememail = input('ENTER MEMBER EMAIL')\n",
    "    timenow = datetime.now().strftime('%c')\n",
    "    with open('member.txt', 'a+') as file:\n",
    "        file.write(f'{memname};{memID};{mememail};{timenow};\\n')\n",
    "        \n",
    "#function to open  an empty list and read the 'member.txt' as it separates each single word data with ';'\n",
    "#the list is changed to a dictionary 'memberdict' then converted bact to list 'memberlist'\n",
    "def member(): \n",
    "    memberlist = []\n",
    "    with open('member.txt','r') as file:\n",
    "      for line in file:\n",
    "          info2 = line.strip().split(';')\n",
    "          memberdict = {'Name':info2[0], 'ID':info2[1],'Email':info2[2], 'Member_Since':info2[3]} \n",
    "          memberlist.append(memberdict)\n",
    "    return memberlist\n",
    "\n",
    "#member() function returns the list of administrator information, if the input matches the name of the member on the memberlist\n",
    "#the member information for the specific name is printed on the output\n",
    "def search_member():\n",
    "    library_banner()\n",
    "    print('Search Member Information')\n",
    "    print('**************************')\n",
    "    memberlist = member()\n",
    "    mem_search = input('Enter Member name to search')\n",
    "    for i in memberlist:\n",
    "        if i['Name'] == mem_search:\n",
    "            print(f\"{i['Name']}, {i['ID']},{i['Email']},{i['Member_Since']}\")\n",
    "            \n",
    "#the member list is printed line by line for the user to refer to when editing\n",
    "#if the old name, ID, Email matches whats in the corresponding list ;the new name or ID or Email replaces it in the list\n",
    "#the new changes are then written in the file\n",
    "def edit_member():\n",
    "    library_banner()\n",
    "    print('Edit Member Information')\n",
    "    print('************************')\n",
    "    memberlist = member()\n",
    "    no = 1\n",
    "    for i in memberlist:\n",
    "      print(f\"{no}){i['Name']}, {i['ID']},{i['Email']},{i['Member_Since']}\")    \n",
    "      no += 1\n",
    "    mem_oldname = input('Enter the Current Member Name')\n",
    "    mem_newname = input('Enter New Member Name')\n",
    "    mem_oldID = input('Enter the Current Member ID')\n",
    "    mem_newID = input('Enter the New Member ID')\n",
    "    mem_oldemail = input('Enter the Current Member Email')\n",
    "    mem_newemail = input('Enter the New Member Email')\n",
    "    for line in memberlist:\n",
    "        if line['Name'] == mem_oldname:\n",
    "            line['Name'] = mem_newname\n",
    "        elif line['ID'] == mem_oldID:\n",
    "            line['ID'] = mem_newID\n",
    "        elif line['Email'] == mem_oldemail:\n",
    "            line['Email'] = mem_newemail \n",
    "            break\n",
    "    with open('member.txt','w') as file:\n",
    "            for i in memberlist:\n",
    "                file.write(f\"{i['Name']};{i['ID']};{i['Email']};{i['Member_Since']};\\n\")\n",
    "                \n",
    "#the member list is printed line by line for the user to refer to when editing\n",
    "#if the input name corresponds with the name in the member list the other names apart from that one are shown in the output\n",
    "def remove_member():\n",
    "    library_banner()\n",
    "    print('Delete Member Information')\n",
    "    print('**************************')\n",
    "    memberlist = ()\n",
    "    no = 1\n",
    "    for i in memberlist:\n",
    "      print(f\"{no}){i['Name']}, {i['ID']},{i['Email']},{i['Member_Since']}\")    \n",
    "      no += 1\n",
    "    deletemember = input('Enter Member Name to delete')\n",
    "    memberlist = [line for line in memberlist if line['Name'] != deletemember]\n",
    "    with open('member.txt', 'w') as file:\n",
    "         for a in memberlist:\n",
    "             file.write(f\"{a['Name']};{a['ID']};{a['Email']};{a['Member_Since']};\\n\")\n",
    "\n",
    "#all member list from member.txt are iterated using the loop 'for i in memberlist'\n",
    "def all_member():\n",
    "    print('View All Member Information')\n",
    "    print('****************************')\n",
    "    memberlist = member()\n",
    "    no = 1\n",
    "    for i in memberlist:\n",
    "        print(f\"{no}){i['Name']}, {i['ID']}, {i['Email']}, {i['Member_Since']}\")\n",
    "        no += 1 \n",
    "\n",
    "#function gives the librarian management options, 'while true' was used to loop the options after every input until logout where it breaks \n",
    "#as break function is used\n",
    "def librarian_management():\n",
    "  while True :\n",
    "     library_banner()\n",
    "     print('1. Add New Librarian Information')\n",
    "     print('2. View All Librarian Information')\n",
    "     print('3. Search Librarian Information')\n",
    "     print('4. Edit Librarian Information')\n",
    "     print('5. Remove Librarian Information')\n",
    "     print('6. Log out')\n",
    "     selection6 = input('Select an Option [1/2/3/4/5/6]')\n",
    "     if selection6 == '1':\n",
    "        new_librarian()\n",
    "     elif selection6== '2':\n",
    "        all_admin()\n",
    "     elif selection6 == '3':\n",
    "        search_librarian()\n",
    "     elif selection6 == '4':\n",
    "        edit_librarian()\n",
    "     elif selection6 == '5':\n",
    "        remove_librarian()\n",
    "     elif selection6 == '6':\n",
    "        print('Logged Out')\n",
    "        break\n",
    "     else:\n",
    "        print('Invalid Option')\n",
    "\n",
    "#function to  add librarian by getting  input from the super administrator or administrator\n",
    "#and creates the file 'librarian.txt' if not created or adds to it the inputs if it already exists\n",
    "#the current time is also recorded and added to the file\n",
    "def new_librarian():\n",
    "    library_banner()\n",
    "    print('Add New Librarian Information')\n",
    "    print('*****************************')\n",
    "    lbname = input('ENTER LIBRARIAN NAME')\n",
    "    lbID = input('ENTER LIBRARIAN ID')\n",
    "    lbemail = input('ENTER LIBRARIAN EMAIL')\n",
    "    timenow = datetime.now().strftime('%c')\n",
    "    with open('librarian.txt', 'a+') as file:\n",
    "        file.write(f'{lbname};{lbID};{lbemail};{timenow};\\n')\n",
    "\n",
    "#function to open  an empty list and read the 'librarian.txt' as it separates each single word data with ';'\n",
    "#the list is changed to a dictionary 'librariandict' then converted bact to list 'librarianlist'\n",
    "def librarian(): \n",
    "    librarianList = []\n",
    "    with open('librarian.txt','r') as file:\n",
    "      for line in file:\n",
    "        info3 = line.strip().split(';')\n",
    "        librariandict = {'Name':info3[0], 'ID':info3[1],'Email':info3[2], 'Joined':info3[3]} \n",
    "        librarianList.append(librariandict)    \n",
    "        return librarianList\n",
    "          \n",
    "#librarian() function returns the list of librarian information, if the input matches the name of the librarian on the librarianList\n",
    "#the librarian information for the specific name is printed on the output\n",
    "def search_librarian():\n",
    "    library_banner()\n",
    "    print('Search Librarian Information')\n",
    "    print('*****************************')\n",
    "    librarianList = librarian()\n",
    "    lb_search = input('Enter Librarian name to search')\n",
    "    for i in librarianList:\n",
    "        if i['Name'] == lb_search:\n",
    "            print(f\"{i['Name']}, {i['ID']},{i['Email']},{i['Joined']}\")\n",
    "            \n",
    "#the librarian list is printed line by line for the user to refer to when editing\n",
    "#if the old name, ID, Email matches whats in the corresponding list ;the new name or ID or Email replaces it in the list\n",
    "#the new changes are then written in the file\n",
    "def edit_librarian():\n",
    "    library_banner()\n",
    "    print('Edit Administrator Information')\n",
    "    print('******************************')\n",
    "    librarianList = librarian()\n",
    "    no = 1\n",
    "    for i in librarianList:\n",
    "      print(f\"{no}){i['Name']}, {i['ID']},{i['Email']},{i['Joined']}\")    \n",
    "      no += 1\n",
    "    oldname = input('Enter the Current Librarian Name')\n",
    "    newname = input('Enter New Librarian Name')\n",
    "    oldID = input('Enter the Current Librarian ID')\n",
    "    newID = input('Enter the New Librarian ID')\n",
    "    oldemail = input('Enter the Current Librarian Email')\n",
    "    newemail = input('Enter the New Librarian Email')\n",
    "    for line in librarianList:\n",
    "        if line['Name'] == oldname:\n",
    "            line['Name'] = newname\n",
    "        elif line['ID'] == oldID:\n",
    "            line['ID'] = newID\n",
    "        elif line['Email'] == oldemail:\n",
    "            line['Email'] = newemail \n",
    "            break\n",
    "    with open('librarian.txt','w') as file:\n",
    "            for a in librarianList:\n",
    "                file.write(f\"{a['Name']};{a['ID']};{a['Email']};{a['Joined']};\\n\")\n",
    "\n",
    "#the librarian list is printed line by line for the user to refer to when editing\n",
    "#if the input name corresponds with the name in the  librarianList the other names apart from that one are shown in the output\n",
    "def remove_librarian():\n",
    "    library_banner()\n",
    "    print('Delete Librarian Information')\n",
    "    print('****************************')\n",
    "    librarianList = librarian()\n",
    "    no = 1\n",
    "    for i in librarianList:\n",
    "      print(f\"{no}){i['Name']}, {i['ID']},{i['Email']},{i['Joined']}\")    \n",
    "      no += 1\n",
    "    deleteLibrarian = input('Enter Librarian Name to delete')\n",
    "    librarianList = [line for line in librarianList if line['Name'] != deleteLibrarian]\n",
    "    with open('librarian.txt', 'w') as file:\n",
    "         for a in librarianList:\n",
    "             file.write(f\"{a['Name']};{a['ID']};{a['Email']};{a['Joined']};\\n\")\n",
    "             \n",
    "#all librarianList from librarian.txt are iterated using the loop 'for i in memberlist'             \n",
    "def all_librarian():\n",
    "    print('View All Librarian Information')\n",
    "    print('*******************************')\n",
    "    librarianList = librarian()\n",
    "    no = 1\n",
    "    for i in librarianList:\n",
    "        print(f\"{no}){i['Name']}, {i['ID']}, {i['Email']}, {i['Joined']}\")\n",
    "        no += 1\n",
    "        \n",
    "#to access book_mannagement fuction librarian has to enter id and password, the id and password if then matches; they are written in 'librarianid.txt'\n",
    "def l_login():\n",
    "     with open('librarianid.txt', 'w') as file:\n",
    "                   file.write(\"L001:password1\\n\")\n",
    "                   file.write(\"L002:password2\\n\")\n",
    "                   file.write(\"L003:password3\\n\")\n",
    "     librarian_id = input(\"Enter your librarian ID: \")\n",
    "     password = input(\"Enter your password: \")\n",
    "\n",
    "     with open('librarianid.txt','r') as file:\n",
    "        for line in file:\n",
    "            id, pwd = line.strip().split(':')\n",
    "            if id == librarian_id and pwd == password:\n",
    "                print(\"Login successful!\")\n",
    "                book_management()\n",
    "                return\n",
    "     print(\"Invalid librarian ID or password\")\n",
    "\n",
    "#function gives the book management options, 'while true' was used to loop the options after every input until logout where it breaks \n",
    "#as break function is used\n",
    "def book_management():\n",
    "   while True:\n",
    "    library_banner()\n",
    "    print('1. Add New Book Information')\n",
    "    print('2. View All Book Information')\n",
    "    print('3. Search Book Information')\n",
    "    print('4. Edit Book Information')\n",
    "    print('5. Remove Book Information')\n",
    "    print('6. Perform Book Loan Process')\n",
    "    print('7. Log Out')\n",
    "    selection7 = input('Select an Option [1/2/3/4/5/6]')\n",
    "    if selection7 == '1':\n",
    "        new_book()\n",
    "    elif selection7 == '2':\n",
    "        all_book()\n",
    "    elif selection7 == '3':\n",
    "        search_book()\n",
    "    elif selection7 == '4':\n",
    "        edit_book()\n",
    "    elif selection7 == '5':\n",
    "        remove_book()\n",
    "    elif selection7 == '6':\n",
    "        book_loan_process()\n",
    "    elif selection7 == '7':\n",
    "        print('Logged Out')\n",
    "        break\n",
    "    else:\n",
    "        print('Invalid Option')\n",
    "        \n",
    "#function to  add book by getting  input from the librarian\n",
    "#and creates the file 'book.txt' if not created or adds to it the inputs if it already exists    \n",
    "def new_book():\n",
    "    library_banner()\n",
    "    print('Add New Book Information')\n",
    "    print('***********************')\n",
    "    bname = input('ENTER BOOK NAME')\n",
    "    bID = input('ENTER BOOK ID')\n",
    "    bauthor = input('ENTER BOOK AUTHOR')\n",
    "    with open('book.txt', 'a+') as file:\n",
    "        file.write(f'{bname};{bID};{bauthor};\\n')\n",
    "        \n",
    "#function to open  an empty list and read the 'book.txt' as it separates each single word data with ';'\n",
    "#the list is changed to a dictionary 'bookdict' then converted bact to list 'booklist'\n",
    "def book(): \n",
    "    booklist = []\n",
    "    with open('book.txt','r') as file:\n",
    "      for line in file:\n",
    "        info4 = line.strip().split(';')\n",
    "        bookdict = {'Name':info4[0], 'ID':info4[1],'Author':info4[2]} \n",
    "        booklist.append(bookdict)\n",
    "    return booklist\n",
    "\n",
    "#book() function returns the list of librarian information, if the input matches the name of the book on the bookList\n",
    "#the book information for the specific name is printed on the output    \n",
    "def search_book():\n",
    "    library_banner()\n",
    "    print('Search Book Information')\n",
    "    print('**************************')\n",
    "    booklist = book()\n",
    "    b_search = input('Enter Book name to search')\n",
    "    for i in booklist:\n",
    "        if i['Name'] == b_search:\n",
    "            print(f\"{i['Name']}, {i['ID']},{i['Author']}\")\n",
    "\n",
    "#the book list is printed line by line for the user to refer to when editing\n",
    "#if the old name, ID, Author matches whats in the corresponding list ;the new name or ID or Author replaces it in the list\n",
    "#the new changes are then written in the file           \n",
    "def edit_book():\n",
    "    library_banner()\n",
    "    print('Edit Book Information')\n",
    "    print('************************')\n",
    "    booklist = book()\n",
    "    no = 1\n",
    "    for i in booklist:\n",
    "      print(f\"{no}){i['Name']}, {i['ID']},{i['Author']}\")    \n",
    "      no += 1\n",
    "    b_oldname = input('Enter the Current Book Name')\n",
    "    b_newname = input('Enter New Book Name')\n",
    "    b_oldID = input('Enter the Current Book ID')\n",
    "    b_newID = input('Enter the New Book ID')\n",
    "    b_oldauthor = input('Enter the Current Author')\n",
    "    b_newauthor = input('Enter the New Author')\n",
    "    for line in booklist:\n",
    "        if line['Name'] == b_oldname:\n",
    "            line['Name'] = b_newname\n",
    "        elif line['ID'] == b_oldID:\n",
    "            line['ID'] = b_newID\n",
    "        elif line['Author'] == b_oldauthor:\n",
    "            line['Author'] = b_newauthor\n",
    "            break\n",
    "    with open('book.txt','w') as file:\n",
    "            for i in booklist:\n",
    "                file.write(f\"{i['Name']};{i['ID']};{i['Author']};\\n\")\n",
    "\n",
    "#the book list is printed line by line for the user to refer to when editing\n",
    "#if the input name corresponds with the name in the  booklist the other names apart from that one are shown in the output\n",
    "def remove_book():\n",
    "    library_banner()\n",
    "    print('Delete Book Information')\n",
    "    print('**************************')\n",
    "    booklist = ()\n",
    "    no = 1\n",
    "    for i in booklist:\n",
    "      print(f\"{no}){i['Name']}, {i['ID']},{i['Author']}\")    \n",
    "      no += 1\n",
    "    deletebook = input('Enter Book Name to delete')\n",
    "    booklist = [line for line in booklist if line['Name'] != deletebook]\n",
    "    with open('book.txt', 'w') as file:\n",
    "         for a in booklist:\n",
    "             file.write(f\"{a['Name']};{a['ID']};{a['Author']};\\n\")\n",
    "\n",
    "#all book list from book.txt are iterated using the loop 'for i in booklist'\n",
    "def all_book():\n",
    "    print('View All Book Information')\n",
    "    print('****************************')\n",
    "    booklist = book()\n",
    "    no = 1\n",
    "    for i in booklist:\n",
    "        print(f\"{no}){i['Name']}, {i['ID']}, {i['Author']}\")\n",
    "        no += 1\n",
    "        \n",
    "#the librarian enters member id, and the book ids; the maximum input for book ids is 5. In case the enters the wrong number of book ids the system\n",
    "#asks the librarian to enter the number again\n",
    "#the current date is subtracted with the date borrowed to get days overdue\n",
    "#if the days overdue is 1 day the respective charge is printed in the output and so on for the other days overdue\n",
    "#the system checks if the overdue days is 0, then the librarian can perform the book loan for the library member\n",
    "#the book loan informtion is then saved on the 'overdue.txt' as we use the 'a+' to append or create and append if the admin.txt \n",
    "#does not exist \n",
    "def book_loan_process():\n",
    "    Member_ID = input(\"Enter the member id\")\n",
    "    BOOK_1 = input(\"Enter the book id 1 borrowed\")\n",
    "    BOOK_2 = input(\"Enter the book id 2 borrowed,IF NO BOOK ENTER [N]\")\n",
    "    BOOK_3 = input(\"Enter the book id 3 borrowed,IF NO BOOK ENTER [N]\")\n",
    "    BOOK_4 = input(\"Enter the book id 4 borrowed,IF NO BOOK ENTER [N]\")\n",
    "    BOOK_5 = input(\"Enter the book id 5 borrowed,IF NO BOOK ENTER [N]\")\n",
    "    Date_Borrowed = datetime.now()\n",
    "    Date_Borrowed_str = Date_Borrowed.strftime('%c')\n",
    "    current_date = datetime.now()\n",
    "    Days_Overdue = (current_date - Date_Borrowed).days\n",
    "    Books_Borrowed = int(input(\"Enter the number of books loaned: \"))\n",
    "    if Books_Borrowed > 5:\n",
    "        print(\"Book limit exceeded\")\n",
    "        Books_Borrowed = int(input(\"Enter the number of books loaned: \"))\n",
    "    if Days_Overdue == 1:\n",
    "         print('Overdue charge 2.00')\n",
    "    elif Days_Overdue == 2:\n",
    "         print('Overdue charge 3.00')\n",
    "    elif Days_Overdue == 3:\n",
    "         print('Overdue charge 4.00')\n",
    "    elif Days_Overdue == 4:\n",
    "         print('Overdue charge 5.00')\n",
    "    elif Days_Overdue == 5:\n",
    "         print('Overdue charge 6.00')\n",
    "    elif Days_Overdue > 5:\n",
    "         print('Overdue charge 10.00')\n",
    "    elif Days_Overdue == 0:\n",
    "         print('Eligible to loan!')\n",
    "         with open('overdue.txt', 'a+') as file:\n",
    "                  file.write(f\"{Member_ID}; {BOOK_1};{BOOK_2};{BOOK_3};{BOOK_4};{BOOK_5}; {Books_Borrowed}; {Date_Borrowed_str}; {Days_Overdue};\\n\")\n",
    "                  print(\"Loan record saved successfully.\")\n",
    "\n",
    "#function to open  an empty list and read the 'overdue.txt' as it separates each single word data with ';'\n",
    "#the list is changed to a dictionary 'loandict' then converted bact to list 'loaned_books'\n",
    "def resetlist():\n",
    "     loaned_books = []\n",
    "     with open('overdue.txt','r') as file:\n",
    "        for line in file:\n",
    "            data = line.strip().split(';')\n",
    "            loandict = {\n",
    "                        'Member_ID': data[0],\n",
    "                        'BOOK_1': data[1],'BOOK_2': data[2],'BOOK_3': data[3],'BOOK_4': data[4],'BOOK_5': data[5],\n",
    "                        'Books_Borrowed': data[6], \n",
    "                        'Date_Borrowed_str': data[7], \n",
    "                        'Days_Overdue': data[8]\n",
    "            }  \n",
    "            loaned_books.append(loandict)\n",
    "     return loaned_books  \n",
    "\n",
    "\n",
    "#function gives the user management options, 'while true' was used to loop the options after every input until logout where it breaks \n",
    "#as break function is used\n",
    "def user_management():\n",
    " while True:\n",
    "    library_banner()\n",
    "    print(\"LIBRARY MEMBER MENU\")\n",
    "    print(\"--------------------------\")\n",
    "    print(\"1. view current loaned books\")\n",
    "    print(\"2. Update profile information\")\n",
    "    print(\"3. search book catalogue\")\n",
    "    print(\"4. logout\")\n",
    "\n",
    "    choice = input(\"Select an Option [1/2/3/4]\")\n",
    "\n",
    "    if choice == '1':\n",
    "        view_current_loaned_books()\n",
    "    elif choice == '2':\n",
    "        update_profile_information()\n",
    "    elif choice == '3':\n",
    "        search_book_catalogue()\n",
    "    elif choice == '4':\n",
    "        print(\"you have been logged out successfully. Goodbye!\")\n",
    "        break\n",
    "    else:\n",
    "        print(\"Invalid choice. Please select again\")\n",
    "    \n",
    "#resetlist() function returns the list of personal member information, if the input matches the id of the member on the loaned_books list\n",
    "def view_current_loaned_books():\n",
    "    library_banner()\n",
    "    print(\"VIEW LOANED BOOKS\")\n",
    "    print(\"******************\")\n",
    "    loaned_books = resetlist()\n",
    "    LOAN_MID = input('Enter Member ID')\n",
    "    for i in loaned_books:\n",
    "        if i['Member_ID'] == LOAN_MID:\n",
    "            print(f\"{i['Member_ID']}, {i['BOOK_1']},{i['BOOK_2']},{i['BOOK_3']},{i['BOOK_4']},{i['BOOK_5']}, {i['Books_Borrowed']}, {i['Date_Borrowed_str']}, {i['Days_Overdue']}\")\n",
    "\n",
    "#the library member is shown their email and name from the memberlist, they can update them\n",
    "#if the current name in memberlist matches the current name they inputed; the changes are reflected in the 'member.txt'\n",
    "def update_profile_information(): \n",
    "    library_banner()\n",
    "    print('update profile Information')\n",
    "    print('***************************')\n",
    "    memberlist = member()\n",
    "    no = 1\n",
    "    for i in memberlist:\n",
    "      print(f\"{no}){i['Name']}, {i['Email']}\")    \n",
    "      no += 1\n",
    "    mem_oldname = input('Enter the Current Member Name')\n",
    "    mem_newname = input('Enter New Member Name')\n",
    "    mem_oldID = input('Enter the Current Member ID')\n",
    "    mem_newID = input('Enter the New Member ID')\n",
    "    mem_oldemail = input('Enter the Current Member Email')\n",
    "    mem_newemail = input('Enter the New Member Email')\n",
    "    for line in memberlist:\n",
    "        if line['Name'] == mem_oldname:\n",
    "            line['Name'] = mem_newname\n",
    "        elif line['ID'] == mem_oldID:\n",
    "            line['ID'] = mem_newID\n",
    "        elif line['Email'] == mem_oldemail:\n",
    "            line['Email'] = mem_newemail \n",
    "            break\n",
    "    with open('member.txt','w') as file:\n",
    "            for i in memberlist:\n",
    "                file.write(f\"{i['Name']};{i['Email']};\\n\")\n",
    "    \n",
    "\n",
    "                \n",
    "#to access user_mannagement fuction member has to enter id and password, the id and password if then matches; they are written in 'librarianid.txt'\n",
    "def login():\n",
    "    with open('memberid.txt', 'w') as file:\n",
    "                   file.write(\"MLB99:password1\\n\")\n",
    "                   file.write(\"MLB51:password2\\n\")\n",
    "                   file.write(\"MLB03:password3\\n\")\n",
    "                   file.write(\"MLB72:password4\\n\")\n",
    "                   file.write(\"MLB15:password5\\n\")\n",
    "        \n",
    "    member_id = input(\"Enter your member ID: \")\n",
    "    password = input(\"Enter your password: \")\n",
    "    \n",
    "    with open('memberid.txt', 'r') as file:\n",
    "        for line in file:\n",
    "            mid, pswd = line.strip().split(':')\n",
    "            if mid == member_id and pswd == password:\n",
    "                print(\"Login successful!\")\n",
    "                user_management()\n",
    "                return\n",
    "    print(\"Invalid member ID or password\")\n",
    "\n",
    "#if the book id inputed by the member is in the 'overdue.txt', it will output that the book is 'not available'\n",
    "#if not found in the file the output is 'available'\n",
    "def search_book_catalogue():\n",
    "    print(\"SEARCH BOOK CATALOGUE\")\n",
    "    print(\"**********************\")\n",
    "    l_search = input(\"Enter the Book ID to Search\")\n",
    "    with open('overdue.txt','r') as file:\n",
    "              for line in file:\n",
    "                  if l_search in line:\n",
    "                      print(\"NOT AVAILABLE\")\n",
    "                      return True\n",
    "    print(\"AVAILABLE\")\n",
    "    return False \n",
    "                    \n",
    "#function gives the  super administrator options, 'while true' was used to loop the options after every input until exit where it breaks \n",
    "#as break function is used   \n",
    "def super_adhpage():\n",
    "  while True :\n",
    "    library_banner()\n",
    "    print('SUPER ADMINISTATOR HOME PAGE')\n",
    "    print('*****************************')\n",
    "    print('i. Administrator Information Management')\n",
    "    print('1. Member Information Management')\n",
    "    print('2. Librarian Information Management')\n",
    "    print('3. Exit')\n",
    "    selection3 = input('Select an Option [i/1/2/3]')\n",
    "    if selection3 == 'i':\n",
    "       admin_management()\n",
    "    elif selection3 == '1':\n",
    "       member_management()\n",
    "    elif selection3 == '2':\n",
    "       librarian_management()\n",
    "    elif selection3 == '3':\n",
    "       print('System Exited')\n",
    "       break\n",
    "    else:\n",
    "       print('Invalid Option')\n",
    "        \n",
    "#function gives the  super administrator options, 'while true' was used to loop the options after every input until exit where it breaks \n",
    "#as break function is used           \n",
    "def ad_hpage():\n",
    "  while True:\n",
    "    library_banner()\n",
    "    print('ADMINISTATOR HOME PAGE')\n",
    "    print('***********************')\n",
    "    print('1. Member Information Management')\n",
    "    print('2. Librarian Information Management')\n",
    "    print('3. Exit')\n",
    "    selection4 = input('Select an Option [1/2/3]')\n",
    "    if selection4 == '1':\n",
    "        member_management()\n",
    "    elif selection4 == '2':\n",
    "        librarian_management()\n",
    "    elif selection4 == '3':\n",
    "        print('System Exited')\n",
    "        break\n",
    "    else:\n",
    "        print('Invalid Option')\n",
    "        \n",
    "#All super administrators use the same password, if incorrect the user will be prompted to the super admin home page         \n",
    "def super_adminlogin():\n",
    "    library_banner()\n",
    "    attempt1 = input('Enter Super Administrator Password')\n",
    "    if attempt1 == 'sAd@kl2024':\n",
    "      print('Welcome Back!')\n",
    "      super_adhpage()\n",
    "    else:\n",
    "      print('INCORRECT PASSWORD')\n",
    "        \n",
    "#All administrators use the same password, if incorrect the user will be prompted to the admin home page        \n",
    "def admin_login():\n",
    "    library_banner()\n",
    "    attempt2 = input('Enter Administrator Password')\n",
    "    if attempt2 == 'Ad@kl2024':\n",
    "      print('Welcome Back!')\n",
    "      ad_hpage()\n",
    "    else:\n",
    "      print('INCORRECT PASSWORD')\n",
    "        \n",
    "#the user has an option to login with the super administrator or administrator, if they choose an invalid number the system prints 'invalid option'     \n",
    "def admin_page():\n",
    "    library_banner()\n",
    "    print('1. Super Administrator Login')\n",
    "    print('2. Administrator Login')\n",
    "    selection2 = input('SELECT ADMINISTRATOR LOGIN TYPE')\n",
    "    if selection2 == '1':\n",
    "       super_adminlogin()\n",
    "    elif selection2 == '2':\n",
    "       admin_login()\n",
    "    else:\n",
    "        print('Invalid Option') \n",
    "\n",
    "#the user has the option to login to administration, librarian and member, if they choose an invalid number the system prints 'invalid option'\n",
    "def home_page():\n",
    "    library_banner()\n",
    "    print('1. ADMINISTRATION LOGIN')\n",
    "    print('2. LIBRARIAN LOGIN')\n",
    "    print('3. LIBRARY MEMBER LOGIN')\n",
    "    selection1 = input('SELECT LOGIN OPTION NUMBER')\n",
    "    if selection1 == '1':\n",
    "        admin_page()\n",
    "    elif selection1 == '2':\n",
    "        l_login()\n",
    "    elif selection1 == '3':\n",
    "        login()\n",
    "    else:\n",
    "        print('Invalid Login option')\n",
    "        \n",
    "home_page()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "517a3bcb-5927-4038-828f-6b01b2f1f5fd",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
